{% set name = "clawpack" %}
{% set version = "5.9.0" %}
{% set setup_py = "setup.py" %}
{% set pyproject_toml = "pyproject.toml" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: ecf9297ca3e483c466fd8ade93192d3c08dec4c30dc1069f501f62c6c4eecb8e

build:
  script:
    - cp {{ RECIPE_DIR }}/{{ setup_py }} .
    - cp {{ RECIPE_DIR }}/{{ pyproject_toml }} .
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
    - numpy
  run:
    - python >=3.6
    - numpy
    - matplotlib-base
    - six

test:
  imports:
    - clawpack
    - clawpack.visclaw
    - clawpack.clawutil
    - clawpack.geoclaw
    - clawpack.amrclaw
  commands:
    - 'python -c "import clawpack; print(\"Clawpack {0} installed\".format(clawpack.__version__))"'
    - 'python -c "from clawpack.clawutil import data; print(\"Clawutil is present.\")"'
    - 'python -c "from clawpack.visclaw import colormaps; print(\"VisClaw is present.\")"'
    - 'python -c "from clawpack.geoclaw import topotools; print(\"GeoClaw is present.\")"'
    - 'python -c "from clawpack.amrclaw import region_tools; print(\"AMRClaw is present.\")"'

about:
  home: https://github.com/clawpack/clawpack
  summary: Package for solving hyperbolic systems of partial differential equations (Python-only components)
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.clawpack.org/contents.html

extra:
  recipe-maintainers:
    - ngam
